	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, GRAY, RED, GRAY
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW, WATER, WATER
	tilepal 0, WATER, GREEN, GREEN, WATER, BROWN, BROWN, GRAY, YELLOW
	tilepal 0, BROWN, BROWN, GRAY, GRAY, YELLOW, YELLOW, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, WATER
